# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rich05' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rich05
  pod 'iosMath', '~> 0.9.4'

end
